### ISSUE TITLE
uinput file can not be opened error on Ubuntu

### ISSUE THREAD

**Issue by widewind2015** [openai-translator/openai-translator#564]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.37

### 系统/浏览器版本 System/Browser version

Ubuntu 22.10

### 复现步骤 Reproduce step

Launching it from the application icon or command line triggers the error.

### 你看到了什么错误？What errors do you see?

with `export RUST_BACKTRACE=full`
```
$ open-ai-translator
thread 'main' panicked at 'uinput file can not be opened: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mouce-0.2.41/src/nix/uinput.rs:34:18
stack backtrace:
   0:     0x55d11952b88a - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d11952b88a - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d11952b88a - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55d11952b88a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d119552e6e - core::fmt::write::h25eb51b9526b8e0c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:     0x55d1195259f5 - std::io::Write::write_fmt::ha9edec5fb1621933
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:     0x55d11952b655 - std::sys_common::backtrace::_print::hf8657cd429fc3452
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55d11952b655 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55d11952cebf - std::panicking::default_hook::{{closure}}::h22a91871f4454152
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:     0x55d11952cbfb - std::panicking::default_hook::h21ddc36de0cd4ae7
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:     0x55d11952d5c9 - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:688:13
  11:     0x55d11952d369 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
  12:     0x55d11952bd3c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55d11952d072 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  14:     0x55d118edbc33 - core::panicking::panic_fmt::hd1d46bcde3c61d72
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  15:     0x55d118edc0e3 - core::result::unwrap_failed::h456a23f68607268c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
  16:     0x55d11926b357 - mouce::nix::uinput::UInputMouseManager::new::h6d61efebea6833ab
  17:     0x55d11926a3db - mouce::nix::NixMouseManager::new::h9e7201ace65fb698
  18:     0x55d118ef9cc4 - app::main::h6b09fbaec56eb6b6
  19:     0x55d119038bd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hecc755aec7e638ae
  20:     0x55d11906b4c9 - std::rt::lang_start::{{closure}}::he2d304f494da087d
  21:     0x55d1195203bc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h203afb3af230319a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:287:13
  22:     0x55d1195203bc - std::panicking::try::do_call::hf68e87013b70f3c5
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  23:     0x55d1195203bc - std::panicking::try::h040ea8f298390ba2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  24:     0x55d1195203bc - std::panic::catch_unwind::h1e17b198887a05fa
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  25:     0x55d1195203bc - std::rt::lang_start_internal::{{closure}}::hfb902d8927e51b86
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:48
  26:     0x55d1195203bc - std::panicking::try::do_call::h354e6eb41f2e7d42
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  27:     0x55d1195203bc - std::panicking::try::h4a39749cd018228c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  28:     0x55d1195203bc - std::panic::catch_unwind::h30bce83b8de61cca
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  29:     0x55d1195203bc - std::rt::lang_start_internal::h8f7e70b1a2558118
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:20
  30:     0x55d118efd035 - main
  31:     0x7f1f22e23510 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  32:     0x7f1f22e235c9 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  33:     0x55d118edc41e - _start
  34:                0x0 - <unknown>
```

### 你期望看到什么？What did you expect to see?

It worked with the early release but I don't know the exact version.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by GerardFinch** [comment]
Yes, i have same problem on Ubuntu 20.04.6 LTS x86_64

```bash
RUST_BACKTRACE=full ./open-ai-translator_0.0.37_amd64.AppImage                                                                                                                    
thread 'main' panicked at 'uinput file can not be opened: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mouce-0.2.41/src/nix/uinput.rs:34:18
stack backtrace:
   0:     0x55ca86e1688a - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ca86e1688a - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ca86e1688a - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ca86e1688a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ca86e3de6e - core::fmt::write::h25eb51b9526b8e0c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:     0x55ca86e109f5 - std::io::Write::write_fmt::ha9edec5fb1621933
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:     0x55ca86e16655 - std::sys_common::backtrace::_print::hf8657cd429fc3452
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55ca86e16655 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55ca86e17ebf - std::panicking::default_hook::{{closure}}::h22a91871f4454152
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:     0x55ca86e17bfb - std::panicking::default_hook::h21ddc36de0cd4ae7
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:     0x55ca86e185c9 - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:688:13
  11:     0x55ca86e18369 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
  12:     0x55ca86e16d3c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55ca86e18072 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  14:     0x55ca867c6c33 - core::panicking::panic_fmt::hd1d46bcde3c61d72
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  15:     0x55ca867c70e3 - core::result::unwrap_failed::h456a23f68607268c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
  16:     0x55ca86b56357 - mouce::nix::uinput::UInputMouseManager::new::h6d61efebea6833ab
  17:     0x55ca86b553db - mouce::nix::NixMouseManager::new::h9e7201ace65fb698
  18:     0x55ca867e4cc4 - app::main::h6b09fbaec56eb6b6
  19:     0x55ca86923bd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hecc755aec7e638ae
  20:     0x55ca869564c9 - std::rt::lang_start::{{closure}}::he2d304f494da087d
  21:     0x55ca86e0b3bc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h203afb3af230319a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:287:13
  22:     0x55ca86e0b3bc - std::panicking::try::do_call::hf68e87013b70f3c5
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  23:     0x55ca86e0b3bc - std::panicking::try::h040ea8f298390ba2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  24:     0x55ca86e0b3bc - std::panic::catch_unwind::h1e17b198887a05fa
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  25:     0x55ca86e0b3bc - std::rt::lang_start_internal::{{closure}}::hfb902d8927e51b86
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:48
  26:     0x55ca86e0b3bc - std::panicking::try::do_call::h354e6eb41f2e7d42
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  27:     0x55ca86e0b3bc - std::panicking::try::h4a39749cd018228c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  28:     0x55ca86e0b3bc - std::panic::catch_unwind::h30bce83b8de61cca
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  29:     0x55ca86e0b3bc - std::rt::lang_start_internal::h8f7e70b1a2558118
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:20
  30:     0x55ca867e8035 - main
  31:     0x7fbc378a0083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  32:     0x55ca867c741e - _start
  33:                0x0 - <unknown>
```

**Comment by toprak** [comment]
same error on arch linux.

**Comment by Xuanwo** [comment]
Seems `mouce` trying to open `/dev/uinput` which requires root permission:

https://github.com/emrebicer/mouce/blob/240ec45af3fcc7a881c4269bca7bfbf0cec8764a/src/nix/uinput.rs#L29-L39

```rust
let manager = UInputMouseManager {
    uinput_file: File::options()
        .write(true)
        .open("/dev/uinput")
        .expect("uinput file can not be opened"),
    callbacks: Arc::new(Mutex::new(HashMap::new())),
    callback_counter: 0,
    is_listening: false,
};
```

**Comment by top** [comment]
To temporarily fix this issue, just change the mode of that file to allow all users to access this character device:
`sudo chmod 0666 /dev/uinput`

This error happens because the program doesn't have permission to access the device `/dev/uinput` as its default permission is `crw-------` which doesn't allow non-root users to access it.

**Comment by Xuanwo** [comment]
> To fix this issue, just change the mode of that file to allow all users to have the permission accessing this character device:
> `sudo chmod 0666 /dev/uinput`

It's not a good choice. It would be better to address the issue from the openai-translator side.

**Comment by top** [comment]
> > To fix this issue, just change the mode of that file to allow all users to have the permission accessing this character device:
> > `sudo chmod 0666 /dev/uinput`
> 
> It's not a good choice. It would be better to address the issue from the openai-translator side.

I agree. It's a risk that allows any user with access to the device the ability to inject input events into the kernel.
However I don't think openai-translator can do anything. It is likely the issue of Tauri I guess.
