### ISSUE TITLE
[Bug] 代码clone，安装依赖之后，使用build报错

### ISSUE THREAD

**Issue by Tetegw** [openai-translator/openai-translator#937]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.63

### 系统/浏览器版本 System/Browser version

Chrome 89.0.4389.114

### 复现步骤 Reproduce step

npm run build-tauri

### 你看到了什么错误？What errors do you see?

[vite:html-inline-proxy] Could not load D:workchatgptopenai-translatorsrc       auriindex.html?html-proxy&inline-css&index=1.css (imported by src/tauri/index.html): Cannot read properties of undefined (reading '1')
error during build:
TypeError: Could not load D:workchatgptopenai-translatorsrc     auriindex.html?html-proxy&inline-css&index=1.css (imported by src/tauri/index.html): Cannot read properties of undefined (reading '1')
    at Object.load (file:///D:/work/chatgpt/openai-translator/node_modules/.pnpm/vite@4.3.9_@types+node@20.4.5/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:37051:65)
    at file:///D:/work/chatgpt/openai-translator/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:24656:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/work/chatgpt/openai-translator/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:24556:28)
    at async file:///D:/work/chatgpt/openai-translator/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23744:75
    at async Queue.work (file:///D:/work/chatgpt/openai-translator/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:24766:32)
 ELIFECYCLE  Command failed with exit code 1.

### 你期望看到什么？What did you expect to see?

正确的打包

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Tetegw** [comment]
`npm run dev-tauri` 是可以正常使用

**Comment by jinmiaoluo** [comment]
是的，我本地也有同样的问题，本地环境的信息如下：

```
system: windows 10 22H2 19045
nodejs: 18.17.1
npm: 9.6.7
pnpm: 8.3.1
```

执行下面的命令

```
pnpm build-tauri
```

会有一样的报错内容。

![image](https://github.com/openai-translator/openai-translator/assets/39730824/90b89e5a-65d1-41db-afd9-d34bd3705080)

**Comment by jinmiaoluo** [comment]
对仓库做了 `git bisect`，错误是这个 commit: 9461fe74cd80fae49218755a6f5d5a1825939f21 开始引入的。

**Comment by cannot-hero** [comment]
我也遇到了这个问题，并且`npm run dev-tauri`也会报错
` Error failed to get cargo metadata: program not found`

**Comment by jinmiaoluo** [comment]
> 我也遇到了这个问题，并且`npm run dev-tauri`也会报错 ` Error failed to get cargo metadata: program not found`

@cannot-hero 你的问题可能是 Rust 没有安装导致的，根据：https://rustup.rs 安装一下应该就能解决 program not found 的问题。

**Comment by jinmiaoluo** [comment]
这个项目的 windows 安装包是在 linux 下通过 tauri 的跨平台编译构建的，如果有需要自己构建 windows 安装包的朋友，请：

1. 根据：https://tauri.app/v1/guides/building/cross-platform/ 安装跨平台编译的依赖
2. 构建：

```bash
npm run build-tauri-renderer
pnpm tauri build --target x86_64-pc-windows-msvc
```

如果遇到 nsis 相关的报错，请执行类似的操作：

```bash
# 替换路径
cp ' /path/to/repo/src-tauri/target/x86_64-pc-windows-msvc/release//OpenAI Translator.exe' open-ai-translator.exe
```

然后重新执行：

```bash
pnpm tauri build --target x86_64-pc-windows-msvc
```

即可
